# Cloudflare IP 抓取配置文件
# 所有参数均为必填项，缺失会导致脚本报错

sources:  # 需要抓取的IP数据源列表。每项可为：
  # - url: 必填，数据源URL
  #   selector: 可选，CSS选择器，优先用此选择器提取IP，未指定则自动智能识别
  - url: https://monitor.gacjie.cn/page/cloudflare/ipv4.html
    selector: 'tbody'     # 优先提取tbody标签内的IP
  - url: https://ip.164746.xyz
    selector: 'td.recommended'        # 优先提取td.recommended标签内的IP
  - url: https://www.nslookup.io/domains/bpb.yousef.isegaro.com/dns-records/#cloudflare
    selector: 'span'        # 优先提取span标签内的IP
  - url: https://cf.090227.xyz
  - url: https://stock.hostmonit.com/CloudFlareYes
    # 未指定selector则自动智能识别
  - url: https://ipdb.030101.xyz/bestcfv4
    # 未指定selector则自动智能识别
pattern: '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'   # 匹配IP的正则表达式
output: "ip.txt"         # 输出文件名，保存所有唯一IP
timeout: 10              # 网络请求超时时间（秒）
log: "fetch_cloudflare_ips.log"   # 日志文件名
max_workers: 4           # 并发线程数，控制静态抓取并发量
log_level: "INFO"        # 日志等级（DEBUG/INFO/WARNING/ERROR）
js_retry: 3              # JS动态抓取最大重试次数
js_retry_interval: 2.0   # JS动态抓取重试间隔（秒） 
max_ips_per_url: 10      # 每个URL最多保留多少个IP（0表示不限制）
per_url_limit_mode: "top"  # 超出限制时的筛选模式: random-随机保留, top-保留页面靠前的
exclude_ips:          # 排除IP列表，支持单个IP和CIDR格式网段
  - "127.0.0.1"        # 排除单个IP，精确匹配
  - "192.168.1.0/24"   # 排除整个网段，CIDR格式 
allowed_regions:        # 只保留这些地区的IP，使用国家/地区代码（如CN、US、HK、JP等），留空或缺省则不过滤
 # - "US"
 # - "HK"
ip_geo_api: "http://ip-api.com/json/{ip}"   # IP归属地API模板，{ip}会被替换为实际IP 
