# Cloudflare IP 抓取配置文件
# 所有参数均为必填项，缺失会导致脚本报错

sources:           # 需要抓取的IP数据源URL列表
  - https://monitor.gacjie.cn/page/cloudflare/ipv4.html
  - https://ip.164746.xyz
  - https://cf.090227.xyz
  - https://stock.hostmonit.com/CloudFlareYes
pattern: "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"   # 匹配IP的正则表达式
output: "ip.txt"         # 输出文件名，保存所有唯一IP
timeout: 10              # 网络请求超时时间（秒）
log: "fetch_cloudflare_ips.log"   # 日志文件名
max_workers: 4           # 并发线程数，控制静态抓取并发量
log_level: "INFO"        # 日志等级（DEBUG/INFO/WARNING/ERROR）
js_retry: 3              # JS动态抓取最大重试次数
js_retry_interval: 2.0   # JS动态抓取重试间隔（秒） 